### ISSUE TITLE
Newly added questions break jquery

### ISSUE THREAD

**Issue by H12** [chi-dragonflies-2015/FAQrator#15]
There are two things that do not happen on newly added questions:
1. Propagation is not stopped, meaning the collapsible expands after clicking the edit/delete buttons.
2. Clicking the edit button no longer triggers the modal from for editing an unanswered question.

**Comment by Faithsend** [comment]
@h12 is this still an issue?

**Comment by H12** [comment]
@Faithsend It would be if we were using Ajax to add new questions. Since we're just re-loading the whole thing on the submission of a new question, it's working fine.
